user:
  name_max: 150
  email_max: 255
  password_min: 6
  avatar_default: "pic.png"
  avatar_height: 200
  avatar_width: 250
post:
  title_size: 300
  content_size: 1000
  number_show: 5
  length_des: 150
comment:
  comment_max_size: 500
tag:
  tag_max: 100
